// Code generated by go-xdr. DO NOT EDIT.
package opaque

import (
	"io"

	"github.com/buildbarn/go-xdr/pkg/runtime"
)

// Type definition "opaque3".

type Opaque3 = [3]byte

func ReadOpaque3(r io.Reader, m *[3]byte) (nTotal int64, err error) {
	var nField int64
	nField, err = runtime.ReadFixedLengthOpaque(r, m[:])
	nTotal += nField
	if err != nil {
		goto done
	}
done:
	return
}

func WriteOpaque3(w io.Writer, m *[3]byte) (nTotal int64, err error) {
	var nField int64
	nField, err = runtime.WriteFixedLengthOpaque(w, m[:])
	nTotal += nField
	if err != nil {
		goto done
	}
done:
	return
}

const Opaque3EncodedSizeBytes = 4

// Type definition "opaque4".

type Opaque4 = [4]byte

func ReadOpaque4(r io.Reader, m *[4]byte) (nTotal int64, err error) {
	var nField int64
	nField, err = runtime.ReadFixedLengthOpaque(r, m[:])
	nTotal += nField
	if err != nil {
		goto done
	}
done:
	return
}

func WriteOpaque4(w io.Writer, m *[4]byte) (nTotal int64, err error) {
	var nField int64
	nField, err = runtime.WriteFixedLengthOpaque(w, m[:])
	nTotal += nField
	if err != nil {
		goto done
	}
done:
	return
}

const Opaque4EncodedSizeBytes = 4

// Type definition "opaque5".

type Opaque5 = [5]byte

func ReadOpaque5(r io.Reader, m *[5]byte) (nTotal int64, err error) {
	var nField int64
	nField, err = runtime.ReadFixedLengthOpaque(r, m[:])
	nTotal += nField
	if err != nil {
		goto done
	}
done:
	return
}

func WriteOpaque5(w io.Writer, m *[5]byte) (nTotal int64, err error) {
	var nField int64
	nField, err = runtime.WriteFixedLengthOpaque(w, m[:])
	nTotal += nField
	if err != nil {
		goto done
	}
done:
	return
}

const Opaque5EncodedSizeBytes = 8
